apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: main
          image: {{ .Values.image }}
          imagePullPolicy: Always
          args:
            - redirect-server
            - all
            - --target
            - {{ required ".Values.target is required" .Values.target | quote}}
            {{- if .Values.preservePath }}
            - --preserve-path
            {{- end }}
          ports:
            - name: http
              containerPort: 8000
